apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "democrm.fullname" . }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "democrm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "democrm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000 
        envFrom:
        - configMapRef:
            name: {{ include "democrm.fullname" . }}-config
        - secretRef:
            name: {{ include "democrm.fullname" . }}-connection-secret
        resources:
          {{- toYaml .Values.resources | nindent 12 }}