apiVersion: v1
kind: Secret
metadata:
  name: {{ include "democrm.fullname" . }}-connection-secret
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
type: Opaque
stringData:
  # MONGODB_URI: {{ .Values.mongodbUri | quote }}
  MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ include "democrm.fullname" . }}-mongodb:27017/{{ .Values.mongodb.auth.database }}?directConnection=false&retryWrites=true&w=majority"
