apiVersion: v1
kind: Secret
metadata:
  name: {{ include "democrm.fullname" . }}-connection-secret
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.mongodbUri | quote }}