apiVersion: v1
kind: Secret
metadata:
  name: mongodb-connection-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://democrm:thigusnkcsu@mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017/democrm?replicaSet=rs0"
 