replicaCount: 2

image:
  repository: pwstaging/demo-crm
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: "512Mi"
  requests:
    cpu: 200m
    memory: "256Mi"

config:
  logLevel: "info"
  persistence: "true"

mongodb:
  auth:
    enabled: true
    username: "democrm"
    password: "mypassword"
    database: "democrm"
  replicaCount: 2

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: sara-cowsay.ddns.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: democrm-tls
      hosts:
        - sara-cowsay.ddns.net


certManager:
  enabled: true
  installCRDs: true
  version: "v1.14.5"
  email: sara.beck.dev@gmail.com


ingress-nginx:
  controller:
    service:
      type: LoadBalancer

service:
  port: 80
